name: "Build and push trustee-attester container image"

env:
  NAME: "trustee-attester"
  REGISTRY: "quay.io/trusted-execution-clusters"

on:
  push:
    branches:
      - main
    paths:
      - 'containerfiles/trustee-attester.container'
      - '.github/workflows/build-trustee-attester-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'containerfiles/trustee-attester.container'
      - '.github/workflows/build-trustee-attester-image.yml'
  workflow_dispatch:

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentially for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-trustee-attester-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: fedora
            base: fedora:rawhide
          - tag: centos-stream
            base: quay.io/centos/centos:stream9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build trustee-attester image (${{ matrix.tag }})
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: ${{ matrix.tag }}
          containerfiles: |
            containerfiles/trustee-attester.container
          context: containerfiles
          oci: true
          build-args: |
            BASE=${{ matrix.base }}

      - name: Push trustee-attester image (${{ matrix.tag }}) to registry
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' && github.repository_owner == 'trusted-execution-clusters'
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
